# Generated by Django 2.0.7 on 2018-07-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('cod_asignatura', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo de la asignatura')),
                ('nom_asignatura', models.CharField(max_length=100, verbose_name='Nombre de la asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('cod_carrera', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Codigo de carrera en sistema')),
                ('nom_carrera', models.CharField(max_length=50, verbose_name='Nombre de la carrera')),
                ('tipo_carrera', models.CharField(choices=[('CIVIL', 'CIVIL'), ('EJECUCION', 'EJECUCION'), ('5 AÑOS', '5 AÑOS')], max_length=1, verbose_name='Tipo de carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_asignatura', models.PositiveIntegerField()),
                ('num_semestre', models.PositiveIntegerField()),
                ('anio_semestre', models.PositiveIntegerField()),
                ('promedio_rendimiento', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aprobados_rendimiento', models.PositiveIntegerField()),
                ('reprobados_rendimiento', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semestre', models.PositiveIntegerField(verbose_name='Numero del semestre')),
                ('anio_semestre', models.PositiveIntegerField(verbose_name='Anio')),
            ],
        ),
    ]
