# Generated by Django 2.0.7 on 2018-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.CharField(choices=[('CIVIL', 'CIVIL'), ('EJECUCION', 'EJECUCION'), ('5 AÑOS', '5 AÑOS')], max_length=10, verbose_name='Tipo de carrera'),
        ),
    ]
