# Generated by Django 2.0.7 on 2018-08-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendimientos', '0002_auto_20180713_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraAsignatura',
            fields=[
                ('codigo_carrera', models.ForeignKey(db_column='codigo_carrera', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rendimientos.Carrera')),
            ],
            options={
                'db_table': 'carrera_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('fono', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('fono', models.CharField(blank=True, max_length=10, null=True)),
                ('vigente', models.NullBooleanField()),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RendimientoCarrera',
            fields=[
                ('codigo_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_asignatura', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('semestre_etiqueta', models.CharField(blank=True, max_length=20, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('promedio_aprobados', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('promedio_reprobados', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('aprobados', models.IntegerField(blank=True, null=True)),
                ('reprobados', models.IntegerField(blank=True, null=True)),
                ('inscritos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rendimiento_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('electividad', models.IntegerField()),
                ('letra', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nombre_corto', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_carrera',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Rendimiento',
        ),
        migrations.DeleteModel(
            name='Semestre',
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='SeccionEstudiante',
            fields=[
                ('id_seccion', models.ForeignKey(db_column='id_seccion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rendimientos.Seccion')),
                ('nota_teoria', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nota_laboratorio', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('situacion_final', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'seccion_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeccionProfesor',
            fields=[
                ('id_seccion', models.ForeignKey(db_column='id_seccion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rendimientos.Seccion')),
                ('teoria', models.NullBooleanField()),
                ('ejercicios', models.NullBooleanField()),
                ('laboratorio', models.NullBooleanField()),
            ],
            options={
                'db_table': 'seccion_profesor',
                'managed': False,
            },
        ),
    ]
