# Generated by Django 2.0.7 on 2018-08-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimientos', '0003_auto_20180801_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_mencion', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('version_plan', models.IntegerField()),
            ],
            options={
                'db_table': 'malla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RendimientoAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_asignatura', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('promedio_aprobados', models.FloatField(blank=True, null=True)),
                ('promedio_reprobados', models.FloatField(blank=True, null=True)),
                ('cantidad_aprobados', models.IntegerField(blank=True, null=True)),
                ('cantidad_reprobados', models.IntegerField(blank=True, null=True)),
                ('cantidad_convalidados', models.IntegerField(blank=True, null=True)),
                ('inscritos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rendimiento_asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RendimientoTipoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo_carrera', models.IntegerField()),
                ('codigo_asignatura', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('promedio_aprobados', models.FloatField(blank=True, null=True)),
                ('promedio_reprobados', models.FloatField(blank=True, null=True)),
                ('cantidad_aprobados', models.IntegerField(blank=True, null=True)),
                ('cantidad_reprobados', models.IntegerField(blank=True, null=True)),
                ('cantidad_convalidados', models.IntegerField(blank=True, null=True)),
                ('inscritos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rendimiento_tipo_carrera',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='asignatura',
            table='asignatura',
        ),
        migrations.AlterModelTable(
            name='carrera',
            table='carrera',
        ),
    ]
